spring:
  application:
    name: itau-code-challange-starter-kit
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:19092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:hello-greeting-template-consumer}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

dynamodb:
  endpoint: ${DYNAMODB_ENDPOINT:http://localhost:8000}
  region: ${DYNAMODB_REGION:us-east-1}
  table-name: ${GREETING_TABLE_NAME:GreetingMessages}
  balance-table-name: ${BALANCE_TABLE_NAME:AccountBalances}
  timeouts:
    connection: ${DYNAMODB_CONNECTION_TIMEOUT:500ms}
    socket: ${DYNAMODB_SOCKET_TIMEOUT:1s}
    api-call-attempt: ${DYNAMODB_API_CALL_ATTEMPT_TIMEOUT:1s}
    api-call: ${DYNAMODB_API_CALL_TIMEOUT:3s}
  retry:
    max-attempts: ${DYNAMODB_MAX_ATTEMPTS:3}

greeting-templates:
  topic-name: ${GREETING_TEMPLATES_TOPIC:greeting-templates}
